trigger:
- main

pool:
  name: my-pool

steps:
- script: echo Hello, world!
  displayName: 'stage-1'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'stage-2'
- script: echo "welcome to my world"
  displayName: 'stage-3'  
- script: echo "This is Bhargav reporting"
  displayName: 'stage-4' 
- script: echo "I am so happy to be here"
  displayName: 'stage-5' 